# Use postgres/example user/assword credentiservices:
services:
  db:
    image: postgres:17.5-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dummypassword
    ports:
      - 0.0.0.0:5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
